#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Create necessary container networks
  ansible.builtin.import_playbook: hyperledger.fabricx.create_container_networks

- name: Start Hyperledger Fabric-X Orderer
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.start

- name: Start Hyperledger Fabric-X Committer
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.start

- name: Create namespaces on Hyperledger Fabric-X Committer
  ansible.builtin.import_playbook: hyperledger.fabricx.fxconfig.create_namespaces
