#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Hyperledger Fabric-X Committer
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.stop

- name: Stop Hyperledger Fabric-X Orderer
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.stop
