#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Hyperledger Fabric-X Committer
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.teardown

- name: Teardown Hyperledger Fabric-X Orderers
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.teardown

- name: Remove container networks
  ansible.builtin.import_playbook: hyperledger.fabricx.remove_container_networks
